version: '3.5'

networks:
  server_network:
    name: server_network

services:
  php:
    image: php:7.4-fpm
    restart: always
    volumes:
      - ./:/var/www/html
    networks:
      - server_network
  nginx:
    image: nginx:1.17.1
    restart: always
    volumes:
      - ./:/var/www/html
      - ./docker/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8080:80
    networks:
      - server_network
